# This workflow will create Python standalone packages

name: PyInstaller

on:
  push:
    tags:
    - '*'

jobs:
  build-unix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: build with pyinstaller
      run: |
        pyinstaller heartmonitor/heartbeatmonitor.py -n HB-Sim2020 --onefile
    - name: See dist directory
      run: ls dist
    - uses: actions/upload-artifact@master
      with:
        name: Unix_latest_HB-Sim2020
        path: dist/HB-Sim2020
    - uses: actions/upload-artifact@master
      with:
        name: Unix_latest_HB-Sim2020
        path: heartmonitor/input/simulation.csv
        
  build-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: build with pyinstaller
      run: |
        pyinstaller heartmonitor/heartbeatmonitor.py -n HB-Sim2020 --onefile
    - name: See dist directory
      run: ls dist
    - uses: actions/upload-artifact@master
      with:
        name: MacOS_latest_HB-Sim2020
        path: dist/HB-Sim2020
    - uses: actions/upload-artifact@master
      with:
        name: MacOS_latest_HB-Sim2020
        path: heartmonitor/input/simulation.csv
        
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: build with pyinstaller
      run: |
        pyinstaller heartmonitor/heartbeatmonitor.py -n HB-Sim2020 --onefile
    - name: See dist directory
      run: ls dist
    - uses: actions/upload-artifact@master
      with:
        name: Windows_latest_HB-Sim2020
        path: dist/HB-Sim2020.exe
    - uses: actions/upload-artifact@master
      with:
        name: Windows_latest_HB-Sim2020
        path: heartmonitor/input/simulation.csv
